### ISSUE TITLE
Running Sumo-Gui

### ISSUE THREAD

**Issue by grnm8** [AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control#10]
Hello after the training is done. I wanted to create visualizations in SUMO of unoptimized traffic vs traffic that is optimized with neural networks. Visuals of before training vs after training. How do you suggest is the best way to do that? Thank you very much

**Comment by AndreaVidali** [comment]
I have just updated the code. Now it is possible to easily test the trained models and compare them using data generated by the test episode.
