### ISSUE TITLE
can you upload tlcs_train.rou.xml file

### ISSUE THREAD

**Issue by ynuwm** [AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control#2]
thank you

**Comment by AndreaVidali** [comment]
The file you requested is produced by running the algorithm, as written in the README: "The TrafficGenerator class contain the function dedicated to defining the route of every vehicle in one episode. The file created is tlcs_train.rou.xml which is placed in the "intersection" folder."

**Comment by ynuwm** [comment]
Thanks for your code, I get it, thank you.
