### ISSUE TITLE
why sumo-gui run so slow

### ISSUE THREAD

**Issue by ynuwm** [AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control#5]
First, thank you for  your code.
But I run so slow both on sumo and sumo-gui, when I change the network from full-connected to CNN. Can you tell me why the simulation run so slow, ten minute gone, I still can't see one episode result.

**Comment by AndreaVidali** [comment]
I am sorry but your problem seems not related to an issue on the repo code. My advice is to profile your code to check where the algorithm is taking so much time.
